version: "3.9"

services:
  password-manager-api:
    build:
      context: .
      dockerfile: ./PasswordManager.WebApi/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./PasswordManager.WebApi/Data:/data
  password-manager-ui:
    build:
      context: ./PasswordManager.UI
      dockerfile: ./Dockerfile
    ports:
      - 8001:80


  
